import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="bg-red-600 min-h-screen">
				<div className="flex-none">
					<Link href={"/"}>Home</Link>
					<Link href={"/pokemons"}>Pokemons</Link>
				</div>
				<div className="bg-blue-300 h-[calc(100vh-24px)]"> {children}</div>
			</body>
		</html>
	);
}
